### ISSUE TITLE
Build fails after Poetry 1.2.0 release

### ISSUE THREAD

**Issue by DrAhmetK** [moneymeets/python-poetry-buildpack#45] opened 2022-08-31 19:07 UTC
GET_POETRY_IGNORE_DEPRECATION=1  doesn't help as well

> -----> Building on the Heroku-22 stack
> -----> Using buildpacks:
>        1. https://github.com/moneymeets/python-poetry-buildpack.git
>        2. heroku/python
>        3. https://github.com/heroku/heroku-buildpack-cli
> -----> Python Poetry app detected
> -----> Using Poetry version from POETRY_VERSION config var: 1.1.13
> -----> Generate requirements.txt with Poetry
> -----> Install Poetry
>        Retrieving Poetry metadata
>        
>        This installer is deprecated, and cannot install Poetry 1.2.0a1 or newer.
>        Additionally, Poetry installations created by this installer cannot `self update` to 1.2.0a1 or later.
>        You should migrate to https://install.python-poetry.org instead. Instructions are available at https://python-poetry.org/docs/#installation.
>        
>        This installer will now exit. If you understand the above warning and wish to proceed anyway, set GET_POETRY_IGNORE_DEPRECATION=1 in the environment and run this installer again.
> -----> Export requirements.txt from Poetry
> /tmp/codon/tmp/buildpacks/6e1a99cb61ad645328dd1c64bd71597add4e2b5b/bin/compile: line 66: poetry: command not found
>  !     Push rejected, failed to compile Python Poetry app.
>  !     Push failed

**Comment by djm** [comment] 2022-08-31 19:18
This is a dupe of #37; a PR has already been opened at https://github.com/moneymeets/python-poetry-buildpack/pull/44

**Comment by zyv** [comment] 2022-09-02 13:38
Resolved in #48.

**Closed as completed** 2022-09-02 13:38 UTC
